version: '3.8'

services:
  orchidbot:
    build: .
    container_name: orchidbot
    restart: unless-stopped
    ports:
      - "5000:5000"
      - "9090:9090"
    volumes:
      - ./data:/app/data
      - ./config/local.yaml:/app/config/local.yaml:ro
      - ./logs:/app/data/logs
    environment:
      - MOCK_HARDWARE=true
      - LOG_LEVEL=INFO
      - DATABASE_URL=sqlite:///data/orchidbot.db
      - INFLUXDB_URL=http://influxdb:8086
    depends_on:
      - influxdb
      - n8n
    networks:
      - orchidbot-network

  influxdb:
    image: influxdb:2.7
    container_name: orchidbot-influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=orchidbot123
      - DOCKER_INFLUXDB_INIT_ORG=orchidbot
      - DOCKER_INFLUXDB_INIT_BUCKET=sensor_data
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=orchidbot-admin-token
    networks:
      - orchidbot-network

  grafana:
    image: grafana/grafana:10.2.0
    container_name: orchidbot-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./config/grafana:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=orchidbot123
      - GF_INSTALL_PLUGINS=grafana-influxdb-datasource
    depends_on:
      - influxdb
    networks:
      - orchidbot-network

  n8n:
    image: n8nio/n8n:1.19.0
    container_name: orchidbot-n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    volumes:
      - n8n-data:/home/node/.n8n
      - ./config/n8n:/home/node/.n8n/workflows
    environment:
      - DB_TYPE=sqlite
      - DB_SQLITE_DATABASE=/home/node/.n8n/database.sqlite
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=orchidbot123
      - WEBHOOK_URL=http://localhost:5678
    networks:
      - orchidbot-network

  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: orchidbot-prometheus
    restart: unless-stopped
    ports:
      - "9091:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - orchidbot-network

  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: orchidbot-mqtt
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./config/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mosquitto-data:/mosquitto/data
      - mosquitto-logs:/mosquitto/log
    networks:
      - orchidbot-network

volumes:
  influxdb-data:
  influxdb-config:
  grafana-data:
  n8n-data:
  prometheus-data:
  mosquitto-data:
  mosquitto-logs:

networks:
  orchidbot-network:
    driver: bridge