# OrchidBot Default Configuration
# This file contains the default settings for the OrchidBot system

# System Information
system:
  name: "OrchidBot"
  version: "1.0.0"
  description: "Automated Hydroponic Orchid Cultivation System"
  location: "Indoor Garden"

# Hardware Configuration
hardware:
  gpio_mode: "BCM"  # BCM or BOARD numbering
  mock_hardware: false  # Set to true for testing without hardware
  
  # Pump control pins (BCM numbering)
  pumps:
    pins: [18, 19, 20, 26]
    timeout: 10.0  # Maximum runtime per activation (seconds)
    max_daily_runtime: 1800  # Maximum total daily runtime (seconds)
    cooldown_period: 60  # Minimum time between activations (seconds)
  
  # Sensor pins and configuration
  sensors:
    # I2C moisture sensors (Chirp sensors)
    moisture:
      i2c_bus: 1
      addresses: [0x20, 0x21, 0x22, 0x23]
      reading_interval: 5.0  # Seconds between readings
      cache_duration: 5.0    # Cache readings for performance
    
    # Overflow detection (float switches)
    overflow:
      pins: [21, 22, 23, 24]
      alert_enabled: true
    
    # Environmental sensors
    environment:
      temperature_pin: 4  # DHT22 or similar
      humidity_pin: 4
      light_sensor_pin: 0  # ADC channel for light sensor
  
  # Status LED pins
  status_leds:
    power: 5
    wifi: 6
    pump_activity: [12, 13, 16, 17]  # One per pump
    alert: 27
  
  # Safety pins
  safety:
    emergency_stop_pin: 25
    watchdog_pin: 11

# Watering Configuration
watering:
  # Moisture thresholds
  moisture_threshold: 40.0    # Start watering below this % (0-100)
  target_moisture: 55.0       # Target moisture level %
  moisture_tolerance: 5.0     # Acceptable variance from target
  
  # Timing settings
  check_interval: 300         # Check sensors every 5 minutes
  watering_interval: 86400    # Minimum time between waterings (24 hours)
  flood_duration: 300         # Flood phase duration (5 minutes)
  drain_duration: 600         # Drain phase duration (10 minutes)
  
  # Advanced settings
  adaptive_watering: true     # Adjust timing based on conditions
  weather_aware: true         # Consider weather in watering decisions
  sunlight_factor: 1.2        # Increase watering on sunny days

# Safety Configuration
safety:
  watchdog_timeout: 30        # System watchdog timeout (seconds)
  pump_timeout: 600           # Maximum pump runtime (10 minutes)
  overflow_shutdown: true     # Stop all pumps on overflow
  emergency_contacts: []      # Phone numbers for alerts
  
  # Limits and thresholds
  max_consecutive_failures: 3 # Stop after this many sensor failures
  temperature_limits:
    min: 15.0  # Celsius
    max: 35.0  # Celsius
  humidity_limits:
    min: 40.0  # Percent
    max: 80.0  # Percent

# Monitoring and Logging
monitoring:
  log_level: "INFO"           # DEBUG, INFO, WARNING, ERROR, CRITICAL
  log_rotation: "daily"       # daily, weekly, monthly
  log_retention: 30           # Keep logs for 30 days
  
  # Data collection
  sensor_logging: true        # Log all sensor readings
  pump_logging: true          # Log pump activities
  system_metrics: true        # Collect system performance metrics
  
  # Prometheus metrics
  prometheus:
    enabled: true
    port: 9090
    metrics:
      - pump_runtime_total
      - cycle_count_total
      - moisture_level_current
      - temperature_current
      - humidity_current

# Web Interface
web:
  enabled: true
  host: "0.0.0.0"
  port: 5000
  debug: false
  
  # Authentication
  auth_required: false        # Set to true for production
  session_timeout: 3600       # 1 hour
  
  # Dashboard settings
  dashboard:
    auto_refresh: 30          # Refresh every 30 seconds
    chart_history: 24         # Show 24 hours of data
    alerts_enabled: true

# API Configuration
api:
  enabled: true
  rate_limiting: true
  max_requests_per_minute: 60
  
  # Webhooks
  webhooks:
    enabled: true
    secret_key: "change-this-secret"
    timeout: 5.0              # Request timeout
    retry_attempts: 3

# External Integrations
integrations:
  # n8n workflow automation
  n8n:
    enabled: false
    webhook_url: "http://localhost:5678/webhook/orchid-system"
    alert_webhook: "http://localhost:5678/webhook/orchid-alert"
    secret: "your-n8n-secret"
  
  # Weather service
  weather:
    enabled: false
    provider: "openweathermap"
    api_key: ""
    location:
      latitude: 40.7128
      longitude: -74.0060
    update_interval: 3600     # Update every hour
  
  # MQTT for IoT integration
  mqtt:
    enabled: false
    broker: "localhost"
    port: 1883
    username: "orchidbot"
    password: ""
    topic_prefix: "orchidbot"
    qos: 1
  
  # Telegram notifications
  telegram:
    enabled: false
    bot_token: ""
    chat_id: ""
    notifications:
      - emergency_stop
      - overflow_detected
      - pump_failure
      - daily_summary

# AI and Machine Learning
ai:
  enabled: false
  model_path: "src/ai/models/orchid_health_v1.tflite"
  
  # Computer vision
  camera:
    enabled: false
    module: "picamera2"       # picamera2 or opencv
    resolution: [1920, 1080]
    photo_interval: 3600      # Take photo every hour
    analysis_enabled: true
  
  # Predictive watering
  predictive:
    enabled: false
    model_type: "regression"
    training_data_days: 30
    prediction_horizon: 24    # Hours ahead to predict

# Orchid Species Profiles
species_profiles:
  default:
    name: "Generic Orchid"
    moisture_range: [40, 60]
    temperature_range: [18, 28]
    humidity_range: [50, 70]
    watering_frequency: "weekly"
    notes: "General orchid care settings"

# Database Configuration
database:
  type: "sqlite"              # sqlite, postgresql, mysql
  path: "data/orchidbot.db"   # For SQLite
  # For other databases:
  # host: "localhost"
  # port: 5432
  # name: "orchidbot"
  # username: "orchidbot"
  # password: ""
  
  # Data retention
  retention_days: 90          # Keep sensor data for 90 days
  backup_enabled: true
  backup_interval: "daily"